### ISSUE TITLE
공연 Entity 생성

### ISSUE THREAD

**Issue by mongmeo-dev** [teamkjk/reservation-project#1]
## DESCRIPTION
공연(영화, 콘서트, 연극, 뮤지컬) Entity 생성하기

## TODO
- [x] 영화 entity 생성
- [x] 콘서트 entity 생성
- [x] 연극 entity 생성
- [x] 뮤지컬 entity 생성
