### ISSUE TITLE
회원가입 기능 추가

### ISSUE THREAD

**Issue by mongmeo-dev** [teamkjk/reservation-project#5]
## DESCRIPTION
회원을 저장하는 기능

## TODO
- [ ] 회원 Entity 정의
- [ ] 회원 저장에 필요한 로직 정의
- [ ] 테스트 코드 작성
